### ISSUE TITLE
Could not determine aspect of TermId 

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#218]
Some errors are being thrown by ``HpoAnnotationEntry.getAspect`` that could probably be dealt with in a better way.
```
Error encountered with entry OMIM:612740	PORPHYRIA, ACUTE HEPATIC	HP:0040284	Very rare							OMIM-CS:miscellaneous > VERY RARE	OMIM:612740	IEA	HPO:skoehler[2019-02-22]
org.monarchinitiative.phenol.base.HpoAnnotationModelException: Could not determine aspect of TermId HP:0040284
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.getAspect(HpoAnnotationEntry.java:727)
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.toBigFileLine(HpoAnnotationEntry.java:743)
	at org.monarchinitiative.phenol.io.annotations.hpo.PhenotypeDotHpoaFileWriter.outputBigFile(PhenotypeDotHpoaFileWriter.java:202)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:69)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:79)
Error encountered with entry OMIM:218800	CRIGLER-NAJJAR SYNDROME, TYPE I	HP:0040284	Very rare							OMIM-CS:miscellaneous > VERY RARE	OMIM:218800	IEA	HPO:skoehler[2019-02-22]
org.monarchinitiative.phenol.base.HpoAnnotationModelException: Could not determine aspect of TermId HP:0040284
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.getAspect(HpoAnnotationEntry.java:727)
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.toBigFileLine(HpoAnnotationEntry.java:743)
	at org.monarchinitiative.phenol.io.annotations.hpo.PhenotypeDotHpoaFileWriter.outputBigFile(PhenotypeDotHpoaFileWriter.java:202)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:69)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:79)
Error encountered with entry OMIM:245348	PYRUVATE DEHYDROGENASE E2 DEFICIENCY; PDHDD	HP:0040284	Very rare							OMIM-CS:miscellaneous > VERY RARE	OMIM:245348	IEA	HPO:skoehler[2019-02-22]
org.monarchinitiative.phenol.base.HpoAnnotationModelException: Could not determine aspect of TermId HP:0040284
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.getAspect(HpoAnnotationEntry.java:727)
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.toBigFileLine(HpoAnnotationEntry.java:743)
	at org.monarchinitiative.phenol.io.annotations.hpo.PhenotypeDotHpoaFileWriter.outputBigFile(PhenotypeDotHpoaFileWriter.java:202)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:69)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:79)
We output a total of 103916 big file lines from internal HPO Annotation files
Error encountered with entry ORPHA:280365	Autosomal semi-dominant severe lipodystrophic laminopathy	HP:0000005	Mode of inheritance								ORPHA:280365	TAS	ORPHA:orphadata[2019-06-21]
org.monarchinitiative.phenol.base.HpoAnnotationModelException: Could not determine aspect of TermId HP:0000005
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.getAspect(HpoAnnotationEntry.java:727)
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.toBigFileLine(HpoAnnotationEntry.java:743)
	at org.monarchinitiative.phenol.io.annotations.hpo.PhenotypeDotHpoaFileWriter.outputBigFile(PhenotypeDotHpoaFileWriter.java:218)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:69)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:79)
Error encountered with entry ORPHA:209902	Hypercholesterolemia due to cholesterol 7alpha-hydroxylase deficiency	HP:0000005	Mode of inheritance								ORPHA:209902	TAS	ORPHA:orphadata[2019-06-21]
org.monarchinitiative.phenol.base.HpoAnnotationModelException: Could not determine aspect of TermId HP:0000005
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.getAspect(HpoAnnotationEntry.java:727)
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.toBigFileLine(HpoAnnotationEntry.java:743)
	at org.monarchinitiative.phenol.io.annotations.hpo.PhenotypeDotHpoaFileWriter.outputBigFile(PhenotypeDotHpoaFileWriter.java:218)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:69)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:79)
Error encountered with entry ORPHA:399805	Male infertility with azoospermia or oligozoospermia due to single gene mutation	HP:0000118	Phenotypic abnormality			HP:0040281					ORPHA:399805	TAS	ORPHA:orphadata[2019-06-21]
org.monarchinitiative.phenol.base.HpoAnnotationModelException: Could not determine aspect of TermId HP:0000118
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.getAspect(HpoAnnotationEntry.java:727)
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.toBigFileLine(HpoAnnotationEntry.java:743)
	at org.monarchinitiative.phenol.io.annotations.hpo.PhenotypeDotHpoaFileWriter.outputBigFile(PhenotypeDotHpoaFileWriter.java:218)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:69)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:79)
Error encountered with entry ORPHA:432	Normosmic congenital hypogonadotropic hypogonadism	HP:0000118	Phenotypic abnormality			HP:0040281					ORPHA:432	TAS	ORPHA:orphadata[2019-06-21]
org.monarchinitiative.phenol.base.HpoAnnotationModelException: Could not determine aspect of TermId HP:0000118
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.getAspect(HpoAnnotationEntry.java:727)
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.toBigFileLine(HpoAnnotationEntry.java:743)
	at org.monarchinitiative.phenol.io.annotations.hpo.PhenotypeDotHpoaFileWriter.outputBigFile(PhenotypeDotHpoaFileWriter.java:218)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:69)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:79)
Error encountered with entry ORPHA:100996	Autosomal recessive spastic paraplegia type 15	HP:0000118	Phenotypic abnormality			HP:0040283					ORPHA:100996	TAS	ORPHA:orphadata[2019-06-21]
org.monarchinitiative.phenol.base.HpoAnnotationModelException: Could not determine aspect of TermId HP:0000118
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.getAspect(HpoAnnotationEntry.java:727)
	at org.monarchinitiative.phenol.annotations.hpo.HpoAnnotationEntry.toBigFileLine(HpoAnnotationEntry.java:743)
	at org.monarchinitiative.phenol.io.annotations.hpo.PhenotypeDotHpoaFileWriter.outputBigFile(PhenotypeDotHpoaFileWriter.java:218)
	at org.monarchinitiative.hpoannotqc.cmd.BigFileCommand.execute(BigFileCommand.java:69)
	at org.monarchinitiative.hpoannotqc.Main.main(Main.java:79)
```

**Comment by pnrobinson** [comment]
Fixed the annotations that go to the Phenotype or Inheritance root.
HP:0040284 -- this is a mistake, it is "Very rare". I think we need to leave this.

**Comment by pnrobinson** [comment]
fixed
