### ISSUE TITLE
CurieUtilBuilder.java requires snakeyaml error

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#275]
While using the OntologyLoader on a Mac with phenol-1.4.4-SNAPSHOT, I got this error
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
	at org.monarchinitiative.phenol.io.utils.CurieUtilBuilder.generate(CurieUtilBuilder.java:56)
	at org.monarchinitiative.phenol.io.utils.CurieUtilBuilder.<clinit>(CurieUtilBuilder.java:22)
	at org.monarchinitiative.phenol.io.OntologyLoader.loadOntology(OntologyLoader.java:35)
```

**Comment by pnrobinson** [comment]
This might be relevant: https://stackoverflow.com/questions/33793441/java-lang-noclassdeffounderror-org-yaml

**Comment by pnrobinson** [comment]
Hmm., I only observed this once and can no longer reproduce the error. Closing.
