### ISSUE TITLE
org.yaml.snakeyaml

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#296]
When using phenol as a library, this seems to get introduced as an additional dependency
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
	at org.monarchinitiative.phenol.io.utils.CurieUtilBuilder.generate(CurieUtilBuilder.java:56)
	at org.monarchinitiative.phenol.io.utils.CurieUtilBuilder.<clinit>(CurieUtilBuilder.java:22)
	at org.monarchinitiative.phenol.io.OntologyLoader.loadOntology(OntologyLoader.java:35)
	at org.jax.l2o.Lirical2Overlap.initDiseaseMap(Lirical2Overlap.java:66)
	at org.jax.l2o.Lirical2Overlap.<init>(Lirical2Overlap.java:25)
	at org.jax.l2o.Main.call(Main.java:36)
```

Investigate why this isn't being inlcuded in the phenol uberjar
any ideas @julesjacobsen

**Comment by pnrobinson** [comment]
Sorry, this was not related to phenol.

**Comment by pnrobinson** [comment]
Still getting this with tukaani but only on Mac?
```
caused by: java.lang.ClassNotFoundException: org.tukaani.xz.XZInputStream
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 22 more
```

The same thing applies to org/tukaani/xz

**Comment by julesjacobsen** [comment]
Which class is this being thrown from? It might be a transitive dependency which has been excluded?

**Comment by pnrobinson** [comment]
unclear what happened, but it is now working.
