### ISSUE TITLE
org/yaml/snakeyaml/Yaml not found

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#358]
Somehow this dependency is "leaking" (this is with latest dev version)
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
	at org.monarchinitiative.phenol.io.utils.CurieUtilBuilder.generate(CurieUtilBuilder.java:56)
	at org.monarchinitiative.phenol.io.utils.CurieUtilBuilder.<clinit>(CurieUtilBuilder.java:22)
	at org.monarchinitiative.phenol.io.OntologyLoader.loadOntology(OntologyLoader.java:35)
(...)
```

see also https://github.com/monarch-initiative/phenol/issues/333
https://github.com/monarch-initiative/phenol/pull/336

**Comment by ielis** [comment]
@pnrobinson is this still an issue in `v2.0.0-RC1`?

**Comment by pnrobinson** [comment]
I will investigate. This was an attempt to deal with that
https://github.com/monarch-initiative/phenol/pull/336
I think that the CurieUtilBuilder is also something that we should either copy paste into phenol or remove since it is just 2 classes and not modular (yet). I tried a slightly different implementation that might be faster, but I did not profile it.
