### ISSUE TITLE
OwlImmutableOntologyLoaderTest error

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/phenol#69]
```
INFO: Graph is simple!
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.036 s <<< FAILURE! - in org.monarchinitiative.phenol.io.owl.OwlImmutableOntologyLoaderTest
[ERROR] testMONDOLoad(org.monarchinitiative.phenol.io.owl.OwlImmutableOntologyLoaderTest)  Time elapsed: 1.634 s  <<< ERROR!
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/mondo/imports/ncbitaxon_import.owl> Cause: purl.obolibrary.org
	at org.monarchinitiative.phenol.io.owl.OwlImmutableOntologyLoaderTest.testMONDOLoad(OwlImmutableOntologyLoaderTest.java:93)
Caused by: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: purl.obolibrary.org
	at org.monarchinitiative.phenol.io.owl.OwlImmutableOntologyLoaderTest.testMONDOLoad(OwlImmutableOntologyLoaderTest.java:93)
Caused by: java.net.UnknownHostException: purl.obolibrary.org
	at org.monarchinitiative.phenol.io.owl.OwlImmutableOntologyLoaderTest.testMONDOLoad(OwlImmutableOntologyLoaderTest.java:93)
```

**Comment by yy20716** [comment]
Sometimes this happens from OWLAPI, i.e. when it cannot access IRIs in import statements due to some external issues such as unstable connections to the Internet. I will check whether there are any options in OWLAPI to minimize this issue. Thank you.

**Comment by pnrobinson** [comment]
I think this is now working, old issue
